### ISSUE TITLE
Where is your supplementary material?

### ISSUE THREAD

**Issue by uchiiii** [srjresearch/BayesianWAND#1]
I read your paper "Revealing Subgroup Structure in Ranked Data Using a Bayesian WAND" and found it very intriguing. Thus, I would like to get deeper insight into the simulation studies and I tried to refer to supplementary material. However, I could not find it online. 
Is it possible to get the link to it?

**Comment by srjresearch** [comment]
Hi Ryosuke,

Thanks for your message. Unfortunately it appears that the supplementary materials aren't available via the journal at this time; we hope this will be resolved soon. To address this issue I've uploaded a PDF copy of the supplementary materials to this repository.

Please do get in touch if you have any more queries.

Thanks,
Stephen

**Comment by uchiiii** [comment]
Hello Stephen,

Thank you for your reply.
I checked that the supplementary materials is now available in this repository. 
I appreciate it.

Best,
Ryosuke
